---
title: "Setup"
teaching: 42
exercises: 47
questions: 
- "FIXME"

objectives:
- "FIXME"

keypoints:
- "FIXME"
source: Rmd
---

```{r, include = FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("00-")
```

## What is this?

This is not really a course. It is a collection of graphs and plots, that we 
would like to keep handy, in order to pick and choose when we get questions
or when running workshops on visualisations.

## What is it not?

## What is here?
Plots are organised by their use. For each type of plot, there are notes on
what it is, what it is typically used for, how we make them, some interesting
variations on the major theme (if there are any. Or if we can imagine them.).
And notes on common pitfalls mistakes and errors using this particular plot.

## What is missing?

Send us an email on kubdatalab@kb.dk or (better), report an issue on 
https://github.com/KUBDatalab/R-graphs/issues if you spot a mistake, 
have a favorite plot we have not included, or are frustrated because we have
not finished the description of a particular plot type that you need now!

Hvad er det her?
Hvad er det ikke?

Det er ikke et R-kursus. Det er eksempler på hvordan man plotter et histogram.
Det er noter om hvad et histogram er. Og hvad man typisk bruger det til.
Det er eksempler på varianter af histogrammer.
og det er "pas-lige-på" noter om hvad man skal være opmærksom på.

Det er ikke et kursus i hvordan du laver en lineær regression. Det er noter om
hvordan du plotter resultatet af din lineære regression.

Vi viser hvordan du plotter en ROC-kurve. Men det er ikke et kursus i hvordan du
får fat på de data der skal bruges til at lave en ROC-kurve. 

Hvis du vil lave et survival plot - så er der noter (eller vil komme til at være)
om hvordan man gør det. Men beregningen af de tal der skal ind i plottet - det
må du selv finde ud af.


{% include links.md %}