---
title: "Flow"
teaching: 0
exercises: 0
questions: 
- "FIXME"

objectives:
- "FIXME"

keypoints:
- "FIXME"
source: Rmd
---

```{r, include = FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("08-")
```

Plots for something that becomes something else - or changes from one thing 
to another. Animationer er også gode til den slags.

## Chord diagram
### What are they?

circlize - statiske 

### What do we use them for?

### how do we make them?

### Interesting variations

Interaktivitet `chorddiag` Her har vi en udfordring - den er ikke tilgængelig
på denne udgave af R - er den for gammel eller for ny?

der er noget med htmlwidgets.



## Networks

### What are they?

Grafer der viser forbindelser mellem ting. Hver ting er repræsenteret med 
en "node" også kaldet "vertice" eller på dansk "knude". Disse knuder er så 
forbundet med "kanter" eller links eller edges. Vi skal nævne alle navnene -
det gør det lettere at google.

tre pakker:
igraph, der både forbereder data, og kan plotte det. ggraph - som plotter i en
gg-verden (og som vist bruges andre steder på denne side). Og networkD3, der 
laver interaktive plots.

### What do we use them for?

### how do we make them?

### Interesting variations

## Sankey

### What are they?
Viser flows fra en ting til en anden. En ting (node) repræsenteres med et 
rektangel. pile eller buer viser flowet mellem dem. 

networkD3 er angiveligt den bedste måde at lave dem. 
### What do we use them for?

### how do we make them?

### Interesting variations

Interaktivitet.

Alluvial diagram - noget med distributioner over tid.

to pakker er værd at kigge på, men tjek lige om der er andre:

`alluvial` og `ggalluvial`

## Arc diagram

### What are they?

En variant af netværks grafer. Her placerer vi alle knuder på rad og række, og 
viser forbindelserne med buer (arcs) mellem dem.

### What do we use them for?

### how do we make them?

### Interesting variations

kan vægtes.

## Edge bundling

Hierarkisk.

### What are they?

### What do we use them for?

### how do we make them?

### Interesting variations


{% include links.md %}