---
title: "Forest plots"
teaching: 0
exercises: 0
questions: 
- "FIXME"

objectives:
- "FIXME"

keypoints:
- "FIXME"
source: Rmd
---

```{r, include = FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("60-")
library(tidyverse)
library(patchwork)
library(knitr)
library(scales)
library(forestplot)
library(palmerpenguins)
library(igraph)
```
igraph har en lidt bøvlet måde at definere grafer på.
Til gengæld giver den adgang til en række funktioner som
fortæller os interessante ting om grafen.

```{r}
actors <- data.frame(name=c("Alice", "Bob", "Cecil", "David",
                            "Esmeralda"),
                     age=c(48,33,45,34,21),
                     gender=c("F","M","F","M","F"))
relations <- data.frame(from=c("Bob", "Cecil", "Cecil", "David",
                               "David", "Esmeralda"),
                        to=c("Alice", "Bob", "Alice", "Alice", "Bob", "Alice"),
                        same.dept=c(FALSE,FALSE,TRUE,FALSE,FALSE,TRUE),
                        friendship=c(4,5,5,2,1,1), advice=c(4,5,5,4,2,3))

relations
g <- graph_from_data_frame(relations, directed=TRUE, vertices=actors)
plot(g)

```


```{r}

```




{% include links.md %}